[target.thumbv7m-none-eabi]
runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -serial tcp:127.0.0.1:21337,server,nodelay -serial tcp:127.0.0.1:31337,nodelay -kernel"
