[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
nix = "0.26.2"
tokio = { version = "1.24.2", default-features = false, features = ["fs", "io-util", "macros", "net", "rt", "process"] }
